import Link from "next/link";

export default function HomePage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center px-4 py-24">
      <div className="max-w-4xl mx-auto text-center space-y-8">
        <div className="space-y-4">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-6xl">
            Combat Sports Intelligence Platform
          </h1>
          <p className="text-xl text-gray-400 max-w-2xl mx-auto">
            AI-powered analytics, rankings, and matchmaking across UFC, PFL, ONE
            Championship, Bellator, RIZIN, KSW, and more.
          </p>
        </div>

        <div className="flex flex-wrap gap-4 justify-center">
          <Link
            href="/fighters"
            className="px-6 py-3 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg transition-colors"
          >
            Browse Fighters
          </Link>
          <Link
            href="/rankings"
            className="px-6 py-3 bg-gray-800 hover:bg-gray-700 text-white font-semibold rounded-lg transition-colors border border-gray-600"
          >
            AI Rankings
          </Link>
          <Link
            href="/matchmaker"
            className="px-6 py-3 bg-gray-800 hover:bg-gray-700 text-white font-semibold rounded-lg transition-colors border border-gray-600"
          >
            Fantasy Matchmaker
          </Link>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 mt-16 text-left">
          <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
            <h2 className="text-lg font-semibold text-white mb-2">
              Semantic Search
            </h2>
            <p className="text-gray-400 text-sm">
              Find fighters, fights, and events using natural language powered
              by pgvector embeddings.
            </p>
          </div>
          <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
            <h2 className="text-lg font-semibold text-white mb-2">
              AI Rankings
            </h2>
            <p className="text-gray-400 text-sm">
              Cross-promotional pound-for-pound rankings generated by LLM
              analysis of fight data.
            </p>
          </div>
          <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
            <h2 className="text-lg font-semibold text-white mb-2">
              Live Debate Rooms
            </h2>
            <p className="text-gray-400 text-sm">
              Real-time discussions with Socket.io — debate the best fighters
              across organizations.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
